-- https://school.programmers.co.kr/learn/courses/30/lessons/131532

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO I
JOIN ONLINE_SALE OS ON I.USER_ID = OS.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), I.GENDER
ORDER BY YEAR, MONTH, GENDER
