-- https://school.programmers.co.kr/learn/courses/30/lessons/131534

WITH JOINED_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT USER_ID) / (SELECT COUNT(USER_ID) FROM JOINED_2021)), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
JOIN JOINED_2021 USING(USER_ID)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
