-- https://school.programmers.co.kr/learn/courses/30/lessons/131118

SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%' AND REVIEW_SCORE IS NOT NULL
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;
