-- https://school.programmers.co.kr/learn/courses/30/lessons/131116

WITH MAX_PRICE_BY_CATEGORY AS (
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY, PRODUCT_NAME
ORDER BY MAX_PRICE DESC
)

SELECT * 
FROM MAX_PRICE_BY_CATEGORY
GROUP BY category; -- 카테고리별 맨 위에 있는 PRODUCT만 조회
