-- https://school.programmers.co.kr/learn/courses/30/lessons/131116

-- Subquery 활용
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS p1
WHERE CATEGORY IN ('과자','국','김치','식용유')
    AND PRICE = (
        SELECT MAX(PRICE)
        FROM FOOD_PRODUCT AS p2
        WHERE p1.CATEGORY = p2.CATEGORY
    )
ORDER BY MAX_PRICE DESC;

-- Subquery + tuple 활용
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC;

-- Window 함수 RANK 활용
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME,
        RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
) pp
WHERE RANKING = 1
ORDER BY MAX_PRICE DESC;
