-- https://school.programmers.co.kr/learn/courses/30/lessons/59043

SELECT INS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS INS
JOIN ANIMAL_OUTS OUTS USING(ANIMAL_ID)
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME;
