-- https://school.programmers.co.kr/learn/courses/30/lessons/157342

WITH HISTORY_CAR_TABLE AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(DURATION), 1) AS AVERAGE_DURATION
FROM HISTORY_CAR_TABLE
GROUP BY CAR_ID
HAVING AVG(DURATION) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
