-- https://school.programmers.co.kr/learn/courses/30/lessons/151141

WITH CAR_RENTAL_WITH_DURATION AS (
SELECT HISTORY_ID, CAR_TYPE, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
CASE
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
    ELSE '90일 이상'
END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
)

SELECT HISTORY_ID, ROUND(DURATION * DAILY_FEE * (1-COALESCE(DISCOUNT_RATE, 0)/100), 0) AS FEE
FROM CAR_RENTAL_WITH_DURATION D
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON D.CAR_TYPE = P.CAR_TYPE AND D.DURATION_TYPE = P.DURATION_TYPE
WHERE D.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
