-- https://school.programmers.co.kr/learn/courses/30/lessons/144856

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY,
    SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM BOOK b, AUTHOR a, BOOK_SALES s
WHERE b.AUTHOR_ID = a.AUTHOR_ID AND s.BOOK_ID = b.BOOK_ID
    AND SALES_DATE LIKE '2022-01%'
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;
