-- https://school.programmers.co.kr/learn/courses/30/lessons/284527

SELECT SUM(SCORE) AS SCORE, e.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES e
JOIN HR_GRADE g ON e.EMP_NO = g.EMP_NO AND g.YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
