# https://school.programmers.co.kr/learn/courses/30/lessons/131123

-- 기본 subquery
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES = (
        SELECT MAX(FAVORITES)
        FROM REST_INFO ri
        WHERE REST_INFO.FOOD_TYPE = ri.FOOD_TYPE
    )
ORDER BY FOOD_TYPE DESC;

-- tuple 비교
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
        SELECT FOOD_TYPE, MAX(FAVORITES)
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    )
ORDER BY FOOD_TYPE DESC;

-- window 함수 활용
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKING
    FROM REST_INFO
) ri
WHERE RANKING = 1
ORDER BY FOOD_TYPE DESC;
